language: {{cookiecutter.language}}
{{cookiecutter.language}}:
  - {{cookiecutter.language_version}}

dist: {{cookiecutter.travis_os}}

# command to install dependencies
install:
  - make all


# command to run tests
script:
  - make test

env: GI_ENV=TEST PYTHONPATH=$TRAVIS_BUILD_DIR/..:$PYTHONPATH BOTO_CONFIG=/tmp/nowhere

# email notifications
notifications:
  email:
    recipients:
      - developers@growthintel.com
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: ""
